development:
  adapter: XXXXXXXX
  database: XXXXXXXX
  pool: XXXXXXXX
  timeout: XXXXXXXX
test:
  adapter: XXXXXXXX
  database: XXXXXXXX
  pool: XXXXXXXX
  timeout: XXXXXXXX

production:
    adapter: XXXXXXXX
    encoding: XXXXXXXX
    database: XXXXXXXX
    username: XXXXXXXX
    password: 
    socket: XXXXXXXX